//USER REGISTRATION //POST
export const USER_REGISTRATION_REQUEST='USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS='USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_ERROR='USER_REGISTRATION_ERROR'

//USER LOGIN //GET
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS= 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR= 'USER_LOGIN_ERROR'

//POST BARANG
export const POST_BARANG_REQUEST= 'POST_BARANG_REQUEST'
export const POST_BARANG_SUCCESS= 'POST_BARANG_SUCCESS'
export const POST_BARANG_ERROR= 'POST_BARANG_ERROR'

//GET BARANG
export const GET_BARANG_REQUEST= 'GET_BARANG_REQUEST'
export const GET_BARANG_SUCCESS= 'GET_BARANG_SUCCESS'
export const GET_BARANG_ERROR= 'GET_BARANG_ERROR'

//DELETE BARANG
export const DELETE_BARANG_REQUEST = 'DELETE_BARANG_REQUEST'
export const DELETE_BARANG_SUCCESS = 'DELETE_BARANG_SUCCESS'
export const DELETE_BARANG_ERROR = 'DELETE_BARANG_ERROR'

export const tambah= 'tambah'
export const kurang= 'kurang'